// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzCMJACao7RK1feqTpoGqrUv3mYX695D8',
    appId: '1:590812912360:web:3e929187ba32a1bf4c075d',
    messagingSenderId: '590812912360',
    projectId: 'kusina-mate',
    authDomain: 'kusina-mate.firebaseapp.com',
    storageBucket: 'kusina-mate.firebasestorage.app',
    measurementId: 'G-XZVJHQKC3L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAM6Ay50JOfe8SymQe5nWv5a5Yph4Dv1B0',
    appId: '1:590812912360:android:f6a90eb8bac5a8ca4c075d',
    messagingSenderId: '590812912360',
    projectId: 'kusina-mate',
    storageBucket: 'kusina-mate.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWfHjmZ72GiP5Rd26QeoJTIUIMV8UpQPo',
    appId: '1:590812912360:ios:f3d8a03982a5be954c075d',
    messagingSenderId: '590812912360',
    projectId: 'kusina-mate',
    storageBucket: 'kusina-mate.firebasestorage.app',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWfHjmZ72GiP5Rd26QeoJTIUIMV8UpQPo',
    appId: '1:590812912360:ios:f3d8a03982a5be954c075d',
    messagingSenderId: '590812912360',
    projectId: 'kusina-mate',
    storageBucket: 'kusina-mate.firebasestorage.app',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzCMJACao7RK1feqTpoGqrUv3mYX695D8',
    appId: '1:590812912360:web:de213b4bdf553b614c075d',
    messagingSenderId: '590812912360',
    projectId: 'kusina-mate',
    authDomain: 'kusina-mate.firebaseapp.com',
    storageBucket: 'kusina-mate.firebasestorage.app',
    measurementId: 'G-1415F8HF6E',
  );

}